# Generated by Django 4.1.4 on 2023-10-20 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagesroom_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activerooms',
            name='users_online',
        ),
        migrations.AddField(
            model_name='activerooms',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
