# Generated by Django 4.1.4 on 2023-10-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_activerooms_users_online_activerooms_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activerooms',
            name='users',
        ),
        migrations.AddField(
            model_name='activerooms',
            name='users_online',
            field=models.IntegerField(default=0),
        ),
    ]
