# Generated by Django 4.1.4 on 2023-12-20 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_activerooms_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activerooms',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='activerooms',
            name='users_online',
        ),
        migrations.CreateModel(
            name='PrivateRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_private', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='added_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
