# Generated by Django 4.1.4 on 2023-12-20 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_activerooms_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activerooms',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activerooms',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PrivateRooms',
        ),
    ]
