# Generated by Django 4.1.4 on 2023-10-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_user_activerooms_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_img',
            field=models.ImageField(default='blank-usr-img.png', upload_to='user_images'),
        ),
    ]
