# Generated by Django 4.1.4 on 2023-10-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_customuser_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesroom',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
