# Generated by Django 4.1.4 on 2023-10-31 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_messagesroom_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(blank=True, related_name='users_direct', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
