# Generated by Django 4.1.4 on 2023-10-31 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_directrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(blank=True, related_name='users_direct', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DirectRooms',
        ),
    ]
