# Generated by Django 4.1.4 on 2023-10-31 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_friendsmodel_delete_directrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsmodel',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='friendsmodel',
            name='users',
        ),
        migrations.AddField(
            model_name='friendsmodel',
            name='users',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
