# Generated by Django 4.1.4 on 2023-10-31 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_friendsmodel_friends_remove_friendsmodel_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsmodel',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='all_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
