# Generated by Django 4.1.4 on 2023-10-31 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_friendsmodel_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsmodel',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
