# Generated by Django 4.1.4 on 2023-10-31 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_friendsmodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsmodel',
            name='users',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
