# Generated by Django 4.1.4 on 2023-10-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_customuser_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsModel',
        ),
    ]
