# Generated by Django 4.1.4 on 2023-10-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_delete_friendsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
