# Generated by Django 4.1.4 on 2023-10-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_directrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directrooms',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
