# Generated by Django 4.1.4 on 2023-11-03 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_directmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directrooms',
            name='author_direct',
        ),
        migrations.RemoveField(
            model_name='directrooms',
            name='friend_direct',
        ),
        migrations.AddField(
            model_name='directrooms',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='direct_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
