# Generated by Django 4.1.4 on 2023-11-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_remove_directrooms_author_direct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directrooms',
            name='default',
            field=models.CharField(default='', editable=False, max_length=4),
        ),
    ]
