# Generated by Django 4.1.4 on 2023-11-05 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_directrooms_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directrooms',
            name='name',
        ),
        migrations.AddField(
            model_name='directrooms',
            name='user_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
