# Generated by Django 4.1.4 on 2023-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_remove_directrooms_name_directrooms_user_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directrooms',
            name='user_f',
        ),
        migrations.AddField(
            model_name='directrooms',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
