# Generated by Django 4.1.4 on 2023-11-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_remove_directrooms_user_f_directrooms_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directrooms',
            old_name='name',
            new_name='author',
        ),
        migrations.AddField(
            model_name='directrooms',
            name='friend',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
